require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude: 
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'spec/**/*'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/api/users/*'
