default: &default
  adapter: "postgresql"
  encoding: "unicode"
  username: "<%= ENV.fetch("POSTGRES_USER") { "admin" } %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "nongkrong-api" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "nongkrong-api" } %>_test

production:
  primary:
    <<: *default
    host: <%= ENV.fetch("POSTGRES_HOST") { "postgresql" } %>-primary
    database: <%= ENV.fetch("POSTGRES_DB") { "nongkrong-api" } %>_production
  read:
    <<: *default
    host: <%= ENV.fetch("POSTGRES_HOST") { "postgresql" } %>-read
    database: <%= ENV.fetch("POSTGRES_DB") { "nongkrong-api" } %>_production
    replica: true
