name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: ruby:3.2.2
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci_1234
    services:
      postgres:
        image: postgres:15.3-bullseye
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci_1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7.0.11-bullseye
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bundle install

      - name: Setup DB
        run: rails db:setup

      - name: Linter
        run: rubocop

      - name: Test
        run: rspec
